name: build
on: 
  push:
      branches:
        - main
        - dev
        - release/*
  pull_request:
    branches:
      - main
      - dev
      - release/*
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        python: ["3.12"]
        toxenvs: ["eospy"]
        # toxenvs: ["py", "coverage", "aioeos", "eospy"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run tox
        run: |
          wget https://www.openssl.org/source/openssl-3.2.1.tar.gz
          tar zxvf openssl-3.2.1.tar.gz
          cd openssl-3.2.1
          ./config --prefix=$HOME/openssl --openssldir=$HOME/openssl shared zlib
          make
          make install
          cd /home/runner/work/antelopy/antelopy/
          export PATH=$HOME/openssl/bin:$PATH
          
          sudo sed -i '/^default = default_sect/a legacy = legacy_sect' $HOME/openssl/openssl.cnf
          sudo sed -i '/^\[default_sect\]/a activate = 1' $HOME/openssl/openssl.cnf
          sudo echo '' >> $HOME/openssl/openssl.cnf
          sudo echo '[legacy_sect]' >> $HOME/openssl/openssl.cnf
          sudo echo 'activate = 1' >> $HOME/openssl/openssl.cnf 
          poetry run tox -e ${{matrix.toxenvs}}
