name: build
on: 
  push:
      branches:
        - main
        - dev
        - release/*
  pull_request:
    branches:
      - main
      - dev
      - release/*
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.12"]
        toxenvs: ["eospy"]
        # python: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        # toxenvs: ["py", "coverage", "aioeos", "eospy"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run tox
        run: | 
          wget https://www.openssl.org/source/openssl-3.2.1.tar.gz
          tar zxvf openssl-3.2.1.tar.gz
          cd openssl-3.2.1
          ./config --prefix=$HOME/openssl --openssldir=$HOME/openssl shared zlib
          make
          make test
          make install
          cd ~
          export PATH=$HOME/openssl/bin:$PATH
          echo openssl version -d
          # sudo sed -i '/^default = default_sect/a legacy = legacy_sect' /etc/ssl/openssl.cnf
          # sudo sed -i '/^\[default_sect\]/a activate = 1' /etc/ssl/openssl.cnf
          # sudo echo "" >> /etc/ssl/openssl.cnf
          # sudo echo "[legacy_sect]" >> /etc/ssl/openssl.cnf
          # sudo echo "activate = 1" >> /etc/ssl/openssl.cnf
          poetry run tox -e ${{matrix.toxenvs}}
